### ISSUE TITLE
Option for selecting only timelines that fall completely in the timeBox

### ISSUE THREAD

**Issue by john-guerra** [ivelascog/TimeSearcherPlus#16]
With dense data and with wide timeBoxes it makes sense to select only the timelines that fall in the box, for example on this image I would have expected to select only the top timelines

<img width="774" alt="image" src="https://github.com/ivelascog/TimeSearcherPlus/assets/1216843/33322345-cb26-4fad-9edd-0a724869a97e">

**Comment by ivelascog** [comment]
partially implemented support for the 2nd option of the previous comment in commit 650555f

**Comment by ivelascog** [comment]
Right now the functionality should be working properly. However, it is necessary to determine a way to switch between "intersection" and "containment" mode (at the moment this is done with a context menu, right click) and possibly a way to visually differentiate the TimeBoxes in each of the modes. Also, it is necessary to take into account that we will have the same problem for the difference between "And" and "or" behaviors.
