### ISSUE TITLE
renderOverviewCanvasSubset is being called without a dataSubset

### ISSUE THREAD

**Issue by john-guerra** [ivelascog/TimeSearcherPlus#24]
I added a [failsafe]( https://github.com/ivelascog/TimeSearcherPlus/blob/8c3d66cd167276d1a053a500761087703d64b82f/src/TimeLineOverview.js#L214) to `renderOverviewCanvasSubset` to fail when it is called without a dataSubset, which was crashing the widget. 

I'm guessing this shouldn't be happening, please check @ivelascog

**Comment by ivelascog** [comment]
I am unable to replicate the error in order to correct it. Could you give me some instructions on how to reproduce the error?

**Comment by ivelascog** [comment]
fixed in 27a8050
