### ISSUE TITLE
New format for specifying predefined filters

### ISSUE THREAD

**Issue by john-guerra** [ivelascog/TimeSearcherPlus#27]
Filter should be definable as an option of the TimeSearcher constructor. Either by:

Option 1: Receives an array of filters ( A filter is an array of the form  `{ selectionDomain: [ [x1, y1], [x2, y2] ] }` from the domain of the data, or `{ selection: [ [px1, py1], [px2, py2] ] }` 
 in pixels)
Option 2:  Receiving an object mapping group name to filters

Option 1: 
```js
filters: [
      {
        selectionDomain: [
          [1.5, -7],
          [2.5, -17]
        ]
      },
      {
        selectionDomain: [
          [6.5, 18],
          [7.5, 6]
        ]
      },
      {
        selectionDomain: [
          [10.5, -7],
          [11.5, -17]
        ]
      }
    ]
```

Option 2:
```js
// Add predefined TimeBoxes
  filters: {
    "Specials 1": [
      {
        selectionDomain: [
          [1.5, -7],
          [2.5, -17]
        ]
      },
      {
        selectionDomain: [
          [6.5, 18],
          [7.5, 6]
        ]
      },
      {
        selectionDomain: [
          [10.5, -7],
          [11.5, -17]
        ]
      }
    ]
  }
```

**Comment by ivelascog** [comment]
It would also be interesting to allow to indicate the aggregation behavior ("And", "or") and the intersection mode ("Intersect" or "Contains").
