### ISSUE TITLE
Add support for point collision to the spatial partitioning algorithm.

### ISSUE THREAD

**Issue by ivelascog** [ivelascog/TimeSearcherPlus#5]
Currently the collision algorithm is designed to work with polylines, expand it to work also with points.

**Comment by john-guerra** [comment]
What does that mean? Can we filter now by all the lines that fall only inside the TimeBox? AND vs OR?

**Comment by ivelascog** [comment]
No, it was a previous step for the feature of filtering all polylines that fall only inside the timebox (which has not yet been implemented). However, I have found another way to do it that instead of being based on points, it is based on the polylines themselves which is more accurate.

The method requires the polyline to cut the TimeBox only on its vertical lines, without cutting the horizontal lines. In this way only the polylines that are inside the TimeBox for the interval in X defined by the TimeBox will be selected. It would be necessary to take into account some special cases, but that would be the idea. 

What do you think?
